s = []

print(s.append(5))
print(s.append(3))
print(s.pop())
print(s.append(2))
print(s.append(8))
print(s.pop())
print(s.pop())
print(s.append(9))
print(s.append(1))
print(s.pop())
print(s.append(7))
print(s.append(6))
print(s.pop())
print(s.pop())
print(s.append(4))
print(s.pop())
print(s.pop())
